# theme = "tokyonight_storm"
# theme = "monokai"
theme = "github_dark"

[editor]
line-number = "relative"
bufferline = "multiple"
  [editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

[editor.lsp]
display-inlay-hints = true

